//constants.h
#ifndef CONSTANTS_H
#define CONSTANTS_H

#define FLIGHT_CODE_COLUMN 0 
#define ORIGIN_COLUMN 1 
#define DESTINATION_COLUMN 2
#define DEPARTURE_TIME_COLUMN 3
#define DEPARTURE_DATE_COLUMN 4 
#define ARRIVAL_TIME_COLUMN 5
#define ARRIVAL_DATE_COLUMN 6
#define PLANE_CODE_COLUMN 7


#define MODEL_COLUMN 0 
#define ROWS_COLUMN 1 
#define LEFT_COLUMN 2 
#define MIDDLE_COLUMN 3 
#define RIGHT_COLUMN 4 

#define FLIGHT_CODE_COLUMN 0 
#define SEAT_NUMBER_COLUMN 1 
#define PASSPORT_COLUMN 2 
#define USER_NAME_COLUMN 3 
#define RESERVATION_CODE_COLUMN 4

//The 0 counts
#define FLIGHT_CODE_CHAR_MAX 6 
#define ORIGIN_CHAR_MAX 4
#define DESTINATION_CHAR_MAX 4
#define DEPARTURE_TIME_CHAR_MAX 6
#define DEPARTURE_DATE_CHAR_MAX 11
#define ARRIVAL_TIME_CHAR_MAX 6
#define ARRIVAL_DATE_CHAR_MAX 11
#define PLANE_CODE_CHAR_MAX 15

#define MODEL_CHAR_MAX 15

#define SEAT_NUMBER_CHAR_MAX 4
#define PASSPORT_CHAR_MAX 10
#define USER_NAME_CHAR_MAX 25
#define RESERVATION_CODE_CHAR_MAX 10

#define ERROR -1
#define OK 0

#define EOSA "FFF" //End Of Seats Array

#endif